// Smoke test for the editor's highlighting pipeline.
//
// Run:  node ui/test/highlight.test.mjs
//
// This exercises the exact path the editor uses: document -> wasm lexer ->
// packed token triples -> per-line HTML. The risky part is splitting a token
// across lines, because a token can contain newlines (a plain span, a block of
// text between two keywords). If that split is wrong the editor silently drops
// or duplicates text, which is the kind of bug that only shows up as "my code
// changed by itself".
//
// The decisive assertion is losslessness: strip the HTML back off and the lines
// must equal the source lines, exactly.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const studio = join(here, "..", "..");

// The module the interface actually loads.
//
// `ui/vendor/textcore.js` is generated by scripts/build-wasm.mjs and carries the
// module as base64; this reads that same string, so the suite and the product
// cannot be looking at different builds.
//
// They were. This file used to read `ui/vendor/textcore.wasm`, which nothing
// wrote - the copy on disk was from an earlier day - so every assertion below
// was being made against a module that no longer existed in `crates/textcore`.
// It went unnoticed for exactly the reason it is worth noting: the bug that
// survived was wrong in the same way in both builds, so testing either one
// looked equally green.
const vendorSrc = readFileSync(join(studio, "ui", "vendor", "textcore.js"), "utf8");
const b64 = /__TEXTCORE_B64\s*=\s*"([^"]+)"/.exec(vendorSrc);
if (!b64) throw new Error("textcore.js has no __TEXTCORE_B64 - run node scripts/build-wasm.mjs");
const { instance } = await WebAssembly.instantiate(Buffer.from(b64[1], "base64"), {});
const TC = instance.exports;
const docHandle = TC.doc_new();

const enc = new TextEncoder();

// The class table is read out of the interface rather than restated here.
//
// It used to be a copy of the array in ui/app.js, and that is the arrangement in
// which a new token kind passes every assertion in this file while the editor
// paints it as nothing at all - the test would be checking its own copy. The
// wasm module is read from the built artefact above for the same reason.
const TOKEN_CLASS = (() => {
  const src = readFileSync(join(studio, "ui", "app.js"), "utf8");
  const m = /const TOKEN_CLASS = \[([^\]]*)\]/.exec(src);
  if (!m) throw new Error("ui/app.js has no TOKEN_CLASS array - did it move?");
  return m[1].split(",").map((s) => s.trim().replace(/^"|"$/g, ""));
})();

// mirrors coreHighlight() in ui/app.js
function highlight(text) {
  const b = enc.encode(text);
  const p = TC.alloc(b.length || 1);
  new Uint8Array(TC.memory.buffer).set(b, p);
  TC.doc_set(docHandle, p, b.length);
  TC.dealloc(p, b.length);
  const count = TC.lex(docHandle);
  const view = new Uint32Array(TC.memory.buffer, TC.lex_ptr(), count * 3);
  const lines = [[]];
  for (let i = 0; i < count; i++) {
    const start = view[i * 3], len = view[i * 3 + 1], kind = view[i * 3 + 2];
    const cls = TOKEN_CLASS[kind] || "";
    const raw = text.slice(start, start + len);
    const parts = raw.split("\n");
    for (let k = 0; k < parts.length; k++) {
      if (k > 0) lines.push([]);
      if (parts[k]) {
        const esc = parts[k].replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        lines[lines.length - 1].push(cls ? '<span class="' + cls + '">' + esc + "</span>" : esc);
      }
    }
  }
  return { lines: lines.map((a) => a.join("")), count };
}

const unesc = (s) => s.replace(/<[^>]+>/g, "").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");

// The packed `[start, len, kind]` triples, unconverted, for tests that need to
// ask about the tokens themselves rather than about the markup.
function rawTokens(text) {
  const b = enc.encode(text);
  const p = TC.alloc(b.length || 1);
  new Uint8Array(TC.memory.buffer).set(b, p);
  TC.doc_set(docHandle, p, b.length);
  TC.dealloc(p, b.length);
  const count = TC.lex(docHandle);
  const view = new Uint32Array(TC.memory.buffer, TC.lex_ptr(), count * 3);
  const out = [];
  for (let i = 0; i < count; i++) {
    out.push({ start: view[i * 3], len: view[i * 3 + 1], kind: view[i * 3 + 2] });
  }
  return out;
}

let pass = 0, fail = 0;
function check(name, got, want) {
  if (JSON.stringify(got) === JSON.stringify(want)) { pass++; console.log("  PASS  " + name); }
  else { fail++; console.log("  FAIL  " + name + "\n        got  " + JSON.stringify(got) + "\n        want " + JSON.stringify(want)); }
}

const CASES = {
  "empty": "",
  "single line": "fn main() {}",
  "trailing newline": "fn main() {}\n",
  "blank lines": "a\n\n\nb",
  "block comment style": "fn a() {\n    // one\n    // two\n    let x = 1\n}\n",
  "long plain span": "fn veryLongIdentifierName() {\n    return someOtherLongName + anotherOne\n}\n",
  "strings with escapes": 'let s = "a \\" b" // not a comment\nlet t = 1\n',
  "unterminated string": 'let s = "never closed\nlet t = 2\n',
  "cyrillic and emoji": "// Список задач\nlet имя = \"значение\"\n// \u{1F600} done\n",
  "punct dense": "fn f(a: Int, b: Str) -> Bool { return a > 1 && b != \"\" }\n",
  "no trailing newline": "fn f() {\n    return 1\n}",
  "fmt with a hole": 'let s = fmt"{name}, hello"\n',
  "fmt with two holes": 'let s = fmt"{a} and {b}"\n',
  "fmt hole on a field path": 'let s = fmt"{p.p_name}"\n',
  "fmt hole holding an expression": 'let s = fmt"{1 + 2}"\n',
  "fmt with no hole": 'let s = fmt"plain text"\n',
  "fmt with doubled braces": 'let s = fmt"{{name}}"\n',
  "fmt with an escaped brace": 'let s = fmt"\\{name}"\n',
  "fmt with empty braces": 'let s = fmt"{}"\n',
  "fmt unterminated": 'let s = fmt"{name}\nlet t = 1\n',
  "plain string with braces": 'let s = "{name}, hello"\n',
};

console.log("highlighting pipeline");
for (const [name, src] of Object.entries(CASES)) {
  const { lines } = highlight(src);
  const sourceLines = src.split("\n");
  check(name + " - line count", lines.length, sourceLines.length);
  check(name + " - lossless", lines.map(unesc), sourceLines);
}

console.log("\ntoken classes reach the markup");
{
  const { lines } = highlight('fn main() -> Int {\n    // note\n    let s = "hi"\n    return 42\n}\n');
  const joined = lines.join("\n");
  check("keyword class present", /class="k"[^>]*>fn</.test(joined), true);
  check("type class present", /class="t"[^>]*>Int</.test(joined), true);
  check("string class present", /class="s"[^>]*>"hi"</.test(joined), true);
  check("comment class present", /class="c"[^>]*>\/\/ note</.test(joined), true);
  check("number class present", /class="n"[^>]*>42</.test(joined), true);
  check("function class present", /class="f"[^>]*>main</.test(joined), true);
}

console.log("\na hole in an fmt string is a variable, and only in an fmt string");
{
  // The rule this section pins down was measured against the compiler, because
  // getting it wrong in either direction is a lie told to the reader:
  //
  //   fmt"{name}"      -> the value
  //   fmt"{p.p_name}"  -> the value
  //   fmt"{1 + 2}"     -> 3
  //   fmt"{}"          -> {}          nothing follows the brace
  //   fmt"{{name}}"    -> {{name}}    a brace does not open an expression
  //   fmt"\{name}"     -> \{name}     escaped, so it cannot open one
  //   "{name}"         -> {name}      a PLAIN string does not interpolate
  //
  // The last one is the one worth having: painting a plain string's braces would
  // promise an interpolation the compiler never performs.
  const HOLES = (src) =>
    rawTokens(src)
      .filter((t) => t.kind === 8)
      .map((t) => src.slice(t.start, t.start + t.len));

  check("a hole is a token of its own", HOLES('fmt"{name}, hello"'), ["{name}"]);
  check("the hole excludes the literal around it", HOLES('fmt"a{name}b"'), ["{name}"]);
  check("a field path is one hole", HOLES('fmt"{p.p_name}"'), ["{p.p_name}"]);
  check("an expression is one hole", HOLES('fmt"{1 + 2}"'), ["{1 + 2}"]);
  check("two holes are two tokens", HOLES('fmt"{a} and {b}"'), ["{a}", "{b}"]);
  check("nested braces stay one hole", HOLES('fmt"{a{b}}"'), ["{a{b}}"]);
  check("an empty hole is not a hole", HOLES('fmt"{}"'), []);
  check("doubled braces are not a hole", HOLES('fmt"{{name}}"'), []);
  check("an escaped brace is not a hole", HOLES('fmt"\\{name}"'), []);
  check("a plain string has no hole", HOLES('"{name}, hello"'), []);
  check("an fmt string with no hole has none", HOLES('fmt"plain text"'), []);
  check("a longer identifier is not fmt", HOLES('let myfmt = "x{name}"'), []);

  const markup = highlight('let s = fmt"{name}, hello"\n').lines.join("\n");
  check("the hole is painted as a variable", /class="v"[^>]*>\{name\}</.test(markup), true);
  check("the literal around it is still a string", /class="s"[^>]*>"/.test(markup), true);

  // Splitting one string token into several must not move a single character.
  const src = 'let s = fmt"{a}, {b} and {c}"\nlet t = "plain {d}"\n';
  check("a split literal is still lossless", highlight(src).lines.map(unesc), src.split("\n"));
}

console.log("\ncomment tokens are comments, in non-ASCII documents too");
{
  // The assertion that the two checks above could not make, and the reason this
  // section exists.
  //
  // The lexer walks UTF-8 bytes; the interface slices a UTF-16 JavaScript
  // string. While the offsets were bytes, `text.slice(start, start + len)`
  // returned text shifted by one unit per extra byte - and every text-level
  // assertion here stayed green, because the pieces still concatenated to the
  // whole document (`slice` clamps at the end) and the per-line comparison
  // strips the markup before comparing. What was wrong was *which class was
  // attached to which text*: a comment on line 1 swallowed line 2 and coloured
  // it as a comment, and `let` came back as a keyword with the wrong letters.
  //
  // So the assertions have to be about the tokens and the classes directly.
  const cases = {
    "cyrillic then code": "// Список задач\nlet имя = 1\n",
    "cyrillic comment then fn": "// Русский комментарий\nfn main() -> Int {\n    return 0\n}\n",
    "emoji in a comment": "// \u{1F600} done\nlet a = 1\n",
    "cyrillic in a string": 'let s = "значение" // note\n',
  };
  for (const [name, src] of Object.entries(cases)) {
    const bad = [];
    for (const t of rawTokens(src)) {
      if (t.kind !== 4) continue;              // 4 = comment
      const raw = src.slice(t.start, t.start + t.len);
      // A line comment ends at the end of its line, so it can neither fail to
      // start with `//` nor contain a newline. The second half is the sharp one:
      // a comment whose length is a byte count over-runs its own newline and
      // eats the next line, and it still starts with `//`.
      if (!raw.startsWith("//")) bad.push("does not start with //: " + JSON.stringify(raw));
      if (raw.includes("\n")) bad.push("runs past its line: " + JSON.stringify(raw));
    }
    check(name + " - every comment token is exactly one line comment", bad, []);

    // And no line that is code may sit inside a comment span.
    const joined = highlight(src).lines.join("\n");
    check(name + " - no code inside a comment span",
      /class="c"[^>]*>[^<]*\b(?:let|fn|return)\b/.test(joined), false);
  }

  // The same document with an ASCII comment must still behave, so the fix cannot
  // have been "stop colouring comments".
  const ascii = "// note\nlet a = 1\n";
  const kinds = rawTokens(ascii).map((t) => [t.kind, ascii.slice(t.start, t.start + t.len)]);
  check("an ascii comment is still a comment", kinds[0], [4, "// note"]);
  check("and the code after it is still code", kinds[2], [1, "let"]);
}

console.log("\nhtml escaping");
{
  const { lines } = highlight('let a = 1 < 2\nlet b = "x > y"\n');
  const joined = lines.join("\n");
  check("angle brackets escaped", joined.includes("&lt;") && joined.includes("&gt;"), true);
  const src2 = 'let a = 1 < 2\nlet b = "x > y"\n';
  check("still lossless after escaping", lines.map(unesc), src2.split("\n"));
}

console.log("\n" + pass + " passed, " + fail + " failed");
process.exit(fail === 0 ? 0 : 1);
