// Build the Rust text core and embed it for the browser.
//
// Run:  node scripts/build-wasm.mjs
//
// Why the wasm is embedded as base64 instead of served as a file.
//
// The Datara server reads files with `file_read`, which returns `Str`. On a
// binary file it returns **zero bytes**, silently:
//
//     POST /api/read  ui/vendor/textcore.wasm
//     {"ok":true,"bytes":0,"content":""}        <- the file is 40070 bytes
//
// So the server cannot serve a .wasm. Rather than work around that with a
// second, non-Datara file server, the module is embedded in a generated
// JavaScript file. That also removes one network round trip at startup and
// keeps the interface working from a single origin.
//
// When `file_read` gains a binary-safe variant (or an `Outcome` that reports
// the failure instead of returning an empty string), this becomes a plain
// `fetch("/vendor/textcore.wasm")` again - see PORTING.md SEAM-5.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const studio = join(here, "..");
const crate = join(studio, "crates", "textcore");
const artifact = join(crate, "target", "wasm32-unknown-unknown", "release", "datara_textcore.wasm");
const outDir = join(studio, "ui", "vendor");
const outFile = join(outDir, "textcore.js");

console.log("building the text core for wasm32-unknown-unknown ...");
execFileSync("cargo", ["build", "--release", "--target", "wasm32-unknown-unknown"], {
  cwd: crate,
  stdio: "inherit",
});

const bytes = readFileSync(artifact);
const b64 = bytes.toString("base64");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  "// GENERATED by scripts/build-wasm.mjs - do not edit.\n" +
    "// The wasm text core, embedded because the Datara server cannot serve a\n" +
    "// binary file (file_read returns 0 bytes on non-UTF-8 content).\n" +
    "window.__TEXTCORE_B64 = " + JSON.stringify(b64) + ";\n",
  "utf8"
);

// The raw module as well, and from the same `bytes`.
//
// It is not what the interface loads - the interface loads the base64 above -
// but it is what `ui/test/highlight.test.mjs` reads, and for a long time nothing
// wrote it: the file on disk was from an earlier build, so the highlighting
// suite was testing a module that no longer existed in the crate. It went
// unnoticed because the assertions it was failing to make were about offsets
// that were wrong in exactly the same way in both builds.
//
// Writing both from one `readFileSync` means they cannot disagree. The test also
// reads the base64 (see the note there), so this file is for the record and for
// the day `file_read` can serve a binary - PORTING.md SEAM-5.
writeFileSync(join(outDir, "textcore.wasm"), bytes);

const kb = (n) => (n / 1024).toFixed(1) + " KB";
console.log("");
console.log("  wasm            " + kb(bytes.length) + "   " + bytes.length + " bytes");
console.log("  embedded        " + kb(statSync(outFile).size) + "   " + outFile);
console.log("  base64 overhead " + (((statSync(outFile).size / bytes.length) - 1) * 100).toFixed(0) + "%");
