// Assemble the interface into ONE self-contained HTML file.
//
// Run:  node scripts/build-ui.mjs
//
// Why this is not just an optimisation.
//
// The Datara runtime gives a socket no timeout, no non-blocking mode and no
// poll: `socket_recv` blocks until data arrives. A connection that connects and
// then sends nothing therefore blocks the server forever, because the accept
// loop is single-threaded. Measured, not theorised:
//
//     $ curl -s .../api/health                    -> 200
//     $ exec 3<>/dev/tcp/127.0.0.1/7878           # connect, send nothing
//     $ curl -s --max-time 5 .../api/health       -> times out
//     $ exec 3<&-                                 # close the idle socket
//     $ curl -s .../api/health                    -> 200 again
//
// A browser opens exactly those connections - preconnect sockets, sockets for a
// request it cancels - so the interface loaded to a blank page. `socket_recv(fd, 0)`
// was tried as a way to poll and it blocks too, so there is no receive timeout to
// be had (see .probe3).
//
// The fix is to remove the reason to open extra connections at all: if the page
// has no subresources, the browser opens one socket, sends one request, and gets
// everything. So React, htm, app.js and the wasm core are all inlined here, and
// the favicon is a data URI so the browser does not ask for it either.
//
// Consequence: this file is generated, and the sources in ui/ are the real
// sources. `ui/index.html` keeps the script tags for development; this build
// replaces them with the file contents.

import { readFileSync, writeFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readIco, pickIco, dataUri } from "./icon-lib.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const studio = join(here, "..");
const ui = join(studio, "ui");

// Which variant to build.
//
//   node scripts/build-ui.mjs          the studio, with the companion
//   node scripts/build-ui.mjs --core   the studio, without it
//
// One interface, two flags. The core variant is the same 4000-line app.js with
// `window.__DS_CORE__` set, and `app.js` reads that in four places: which panel
// tabs exist, whether the bar carries the companion's plug, whether the palette
// offers to start it, and whether the settings screen lists it. Nothing else
// differs - the compiler, the editor, the tree, the explorer, Layout, Project,
// git and search are the same code in both.
const CORE = process.argv.includes("--core");
const outFile = CORE ? "studio-core.html" : "studio.html";

const index = readFileSync(join(ui, "index.html"), "utf8");

// The Datara mark, as data URIs. `index.html` carries the tokens rather than
// the bytes so that the artwork has one source - `ui/mark.ico`, generated by
// `scripts/build-icons.mjs` from the geometry in `scripts/mark.mjs` - and so
// that the file stays readable.
//
// Why `ui/mark.ico` and not `assets/datara.ico`: the assets copy used to be an
// orange palm in a yellow square, which is not the mark the interface draws.
// Both paths now hold the same generated bytes, but the UI reads the one inside
// `ui/` so that a stale file in `assets/` cannot put a different icon in the
// browser tab than the one in the window.
//
// Two sizes, and each is measured rather than assumed.
//
// 32 px backs everything small: the mark beside a `.dtr` file in the explorer,
// the mark in the title bar, and the browser tab. It is deliberately NOT the
// 16 px entry, which is what a 13-16 px drawing would suggest - a 16 px CSS box
// is up to 32 device px on a 200% display, so the 16 px entry was being
// upsampled 3x there.
//
// 128 px is for the title screen, where the mark is drawn at 56 px.
const mark = readIco(join(studio, "ui", "mark.ico"));
const uri32 = dataUri(pickIco(mark, 32));
const uri128 = dataUri(pickIco(mark, 128));
// The language file icon is the actual Datara logo supplied by the language
// project, not the compact window mark. Keep the two identities separate:
// the logo is what people recognise beside a `.dtr` file.
const dtrLogo = "data:image/png;base64," +
  readFileSync(join(studio, "assets", "datara-logo.png")).toString("base64");

// A literal `</script` inside a string would end the block early.
const guard = (js) => js.replace(/<\/script/gi, "<\\/script");

let inlined = 0;
const out = index
  .replace(/<script src="([^"]+)"><\/script>/g, (whole, src) => {
    // /ui/app.js -> ui/app.js, /vendor/x.js -> ui/vendor/x.js
    const rel = src.startsWith("/vendor/")
      ? "ui/vendor/" + src.slice("/vendor/".length)
      : src.replace(/^\//, "");
    const file = join(studio, rel);
    let body;
    try {
      body = readFileSync(file, "utf8");
    } catch (e) {
      throw new Error("cannot inline " + src + " (looked for " + file + ")");
    }
    inlined++;
    return "<script>\n" + guard(body) + "\n</script>";
  })
  // The variant flag, injected before any inlined script runs. It has to be a
  // separate block rather than a line prepended to app.js: `tauri-bridge.js`
  // runs first and reads nothing of this, but a reader looking for `__DS_CORE__`
  // should find it declared in the page rather than buried in a 4000-line file.
  //
  // Matched loosely on whitespace - an earlier version of this expected
  // `<script>\n/* __DS_VARIANT__ */\n</script>` exactly, and threw when the
  // comment sat on the same line as the tags. The sentinel is what matters, not
  // the layout around it.
  .replace(/<script>\s*\/\* __DS_VARIANT__ \*\/\s*<\/script>/, CORE
    ? "<script>\n/* built with --core: the studio without the companion */\n" +
      "window.__DS_CORE__ = true;\n</script>"
    : "<script>\n/* the full studio */\nwindow.__DS_CORE__ = false;\n</script>")
  // the favicon is a data URI too: a real icon, but still no second request,
  // which is the whole point of the single-file build (see the note above)
  .replace(/__DATARA_FAVICON__/g, uri32)
  .replace(/__DATARA_ICON_32__/g, uri32)
  .replace(/__DATARA_ICON_128__/g, uri128)
  .replace(/__DATARA_DTR_LOGO__/g, dtrLogo);

if (inlined === 0) throw new Error("no script tags were inlined - did index.html change?");
if (out.includes("__DATARA_")) throw new Error("an icon token was left unsubstituted in index.html");
if (out.includes("__DS_VARIANT__")) {
  throw new Error("the __DS_VARIANT__ placeholder was not replaced - index.html moved it");
}
// The flag has to be settled before `app.js` runs, and `app.js` reads it at load
// time, so a build where it is missing would silently produce the full studio
// under a core filename. Check the order rather than trusting the layout.
const variantAt = out.indexOf("__DS_CORE__ = ");
const appAt = out.indexOf("const CORE =");
if (variantAt < 0 || appAt < 0 || variantAt > appAt) {
  throw new Error("the variant flag is not set before app.js reads it");
}

// The mark beside a .dtr file is drawn at 13-16 px CSS, so it needs at least
// 32 px of source: a 200% display asks for 32 device pixels and the browser
// upsamples anything smaller. This is a guard rather than a comment because
// backing it with the 16 px entry was a reasonable-looking choice that measured
// worst of the seven entries at every scaling, and cost 6.4x the crispness at
// 150% - a regression nothing else here would have caught.
const widthOf = (uri) => {
  const b = Buffer.from(uri.slice(uri.indexOf(",") + 1), "base64");
  if (b.length < 24 || b.readUInt32BE(12) !== 0x49484452) throw new Error("icon is not a PNG");
  return b.readUInt32BE(16);
};
const used = /\.fico-dtr\{background-image:url\((data:image\/png;base64,[^)]+)\)/.exec(out);
if (!used) throw new Error("no .fico-dtr background image in the built stylesheet");
const dtrIcon = widthOf(used[1]);
if (dtrIcon < 32) {
  throw new Error(".fico-dtr is backed by a " + dtrIcon + "px icon; it is drawn at up to " +
    "16px CSS and needs >= 32px for a 200% display");
}

const target = join(ui, outFile);
writeFileSync(target, out, "utf8");

const kb = (n) => (n / 1024).toFixed(1) + " KB";
console.log("");
console.log("  variant   " + (CORE ? "core (no companion)" : "full studio"));
console.log("  inlined   " + inlined + " script blocks");
console.log("  icon      .fico-dtr backed by the " + dtrIcon + "px entry");
console.log("  output    " + kb(statSync(target).size) + "   " + target);
console.log("  requests  the browser needs exactly 1 to load the interface");
