@echo off
REM Build the Tauri desktop shell.
REM
REM Two things this has to get right, and both are the reason it is a script
REM rather than one line in the README:
REM
REM   1. MSVC's link.exe must precede Git-Bash's GNU link, or linking fails with
REM      `extra operand '/DEBUG:NONE'` - which reads like a compiler bug and is
REM      not one. That ordering is set up by scripts\msvc-env.sh, sourced below.
REM   2. cargo lives in %USERPROFILE%\.cargo\bin and is not on PATH by default.
REM
REM If this project has been MOVED, the first build after the move fails inside
REM the tauri build script, quoting a path that no longer exists - it names the
REM old location, then target\release\build\tauri-HASH\out\permissions\app\
REM autogenerated\commands\app_hide.toml. (Written without redirection characters
REM on purpose: cmd acts on those even inside a REM line.)
REM
REM That is the build cache, not the source: target\ records absolute paths in
REM its build-script output, and every child of it survives a move, which is what
REM makes it confusing. Throw it away once and rebuild:
REM
REM   cargo clean --manifest-path src-tauri\Cargo.toml
REM
REM Measured after the studio moved to D:\IDE datara: 3284 files / 1.2 GiB
REM removed, then 5m 24s to rebuild. target\ is gitignored, so it is disposable
REM by design. An already-built exe does NOT need this - studio_dir() walks up
REM looking for src\main.dtr, so a binary keeps working wherever it is moved.
REM
REM Usage:  scripts\build-desktop.cmd

setlocal
cd /d "%~dp0.."

set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"

where cargo >nul 2>&1
if errorlevel 1 (
  echo   cargo is not on PATH. Install Rust from https://rustup.rs
  exit /b 1
)

echo   setting up the MSVC environment ...
call bash -lc "source scripts/msvc-env.sh && echo PATH_READY"
if errorlevel 1 (
  echo.
  echo   Could not find a Visual Studio installation with the C++ toolchain.
  echo   Install "Desktop development with C++" from the Visual Studio Installer.
  exit /b 1
)

REM The build inputs, in the order that makes them inputs.
REM
REM Three of the four write gitignored files that a later step reads, so a fresh
REM checkout has none of them and the order is not cosmetic:
REM
REM   build-wasm.mjs   -> ui\vendor\textcore.js, which build-ui.mjs INLINES.
REM                       Without it the interface build dies on
REM                       "cannot inline /vendor/textcore.js". Measured on a
REM                       fresh checkout (git archive HEAD into an empty
REM                       directory) - it was missing from this script.
REM   build-icons.mjs  -> src-tauri\icons\ and ui\mark.ico. build-ui.mjs embeds
REM                       ui\mark.ico, so this must come BEFORE it. This script
REM                       had them the other way round, so the interface always
REM                       embedded whatever ui\mark.ico already held - the
REM                       checked-in copy on a fresh tree, the previous run's
REM                       otherwise. Silent either way, and it shows up only when
REM                       the geometry in scripts\mark.mjs changes: the window
REM                       icon gets the new mark and the title bar keeps the old
REM                       one, which is the exact drift scripts\mark.mjs exists to
REM                       prevent.
REM   build-ui.mjs     -> ui\studio.html and, with --core, ui\studio-core.html.
REM                       BOTH are declared resources in tauri.conf.json, and
REM                       tauri-build fails the build if a declared resource is
REM                       missing. --core is what `?core=1` serves.
echo   building the self-contained interface ...
node scripts\build-wasm.mjs
if errorlevel 1 exit /b 1
node scripts\build-icons.mjs
if errorlevel 1 exit /b 1
node scripts\build-ui.mjs
if errorlevel 1 exit /b 1
node scripts\build-ui.mjs --core
if errorlevel 1 exit /b 1

if not exist "src-tauri\dist\index.html" (
  echo   src-tauri\dist\index.html is missing.
  exit /b 1
)

echo   building the Datara server resource ...
REM The Tauri bundle copies src\main.exe as studio\src\main.exe. Rebuilding
REM only the Rust shell leaves that resource stale, so an installer can report
REM an older version and still contain the old filesystem commands.
bash -lc "source scripts/msvc-env.sh >/dev/null && forgen build src/main.dtr"
if errorlevel 1 exit /b 1

echo   building the desktop shell ...
REM bash -lc so the exported MSVC environment survives into cargo
bash -lc "source scripts/msvc-env.sh >/dev/null && cargo build --release --manifest-path src-tauri/Cargo.toml"
if errorlevel 1 exit /b 1

echo.
echo   built: src-tauri\target\release\datara-studio.exe
exit /b 0
