@echo off
REM Build the Tauri desktop shell.
REM
REM Two things this has to get right, and both are the reason it is a script
REM rather than one line in the README:
REM
REM   1. MSVC's link.exe must precede Git-Bash's GNU link, or linking fails with
REM      `extra operand '/DEBUG:NONE'` - which reads like a compiler bug and is
REM      not one. That ordering is set up by scripts\msvc-env.sh, sourced below.
REM   2. cargo lives in %USERPROFILE%\.cargo\bin and is not on PATH by default.
REM
REM If this project has been MOVED, the first build after the move fails inside
REM the tauri build script, quoting a path that no longer exists - it names the
REM old location, then target\release\build\tauri-HASH\out\permissions\app\
REM autogenerated\commands\app_hide.toml. (Written without redirection characters
REM on purpose: cmd acts on those even inside a REM line.)
REM
REM That is the build cache, not the source: target\ records absolute paths in
REM its build-script output, and every child of it survives a move, which is what
REM makes it confusing. Throw it away once and rebuild:
REM
REM   cargo clean --manifest-path src-tauri\Cargo.toml
REM
REM Measured after the studio moved to D:\IDE datara: 3284 files / 1.2 GiB
REM removed, then 5m 24s to rebuild. target\ is gitignored, so it is disposable
REM by design. An already-built exe does NOT need this - studio_dir() walks up
REM looking for src\main.dtr, so a binary keeps working wherever it is moved.
REM
REM Usage:  scripts\build-desktop.cmd

setlocal
cd /d "%~dp0.."

set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"

where cargo >nul 2>&1
if errorlevel 1 (
  echo   cargo is not on PATH. Install Rust from https://rustup.rs
  exit /b 1
)

echo   setting up the MSVC environment ...
call bash -lc "source scripts/msvc-env.sh && echo PATH_READY"
if errorlevel 1 (
  echo.
  echo   Could not find a Visual Studio installation with the C++ toolchain.
  echo   Install "Desktop development with C++" from the Visual Studio Installer.
  exit /b 1
)

echo   building the desktop shell ...
REM bash -lc so the exported MSVC environment survives into cargo
bash -lc "source scripts/msvc-env.sh >/dev/null && cargo build --release --manifest-path src-tauri/Cargo.toml"
if errorlevel 1 exit /b 1

echo.
echo   built: src-tauri\target\release\datara-studio.exe
exit /b 0
