#!/usr/bin/env python3
"""Generate probes/bool_field/main.dtr - bisect which struct layout breaks.

A struct containing Bool fields, stored in a List and read back, can return
wrong values. This generator emits one struct per candidate layout so the
trigger can be isolated instead of guessed at.
"""

import pathlib

VARIANTS = {
    "V0_exact_subscription": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Bool"),
        ("cancelled", "Bool"), ("delivery_count", "Int"), ("muted", "List<Str>"),
    ],
    "V1_no_muted": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Bool"),
        ("cancelled", "Bool"), ("delivery_count", "Int"),
    ],
    "V2_bools_last": [
        ("id", "Int"), ("kind", "Str"), ("scope_id", "Int"),
        ("deferred_mode", "Bool"), ("cancelled", "Bool"),
    ],
    "V3_bools_then_int": [
        ("id", "Int"), ("kind", "Str"), ("scope_id", "Int"),
        ("deferred_mode", "Bool"), ("cancelled", "Bool"), ("delivery_count", "Int"),
    ],
    "V4_bools_as_int": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Int"),
        ("cancelled", "Int"), ("delivery_count", "Int"), ("muted", "List<Str>"),
    ],
}

HEAD = '''//! GENERATED by scripts/gen_bool_probe.py - do not edit by hand.
//!
//! Probe: a struct containing Bool fields, pushed into a List and read back,
//! can return wrong values. One struct per candidate layout, so the trigger is
//! isolated by observation rather than guessed at.
//!
//! Every variant is constructed with deferred_mode=false and cancelled=false.
//! Any line printing `true` is a miscompile.

fn b2s(v: Bool) -> Str {
    mut res = "false"
    if v {
        res = "true"
    }
    return res
}
'''


def literal_value(field, typ):
    return {
        "id": "id",
        "kind": "kind",
        "scope_id": "scope_id",
        "subsystem": '""',
        "priority": "10",
        "scope": '"document"',
        "muted": "[]",
    }.get(field, "false" if typ == "Bool" else "0")


def main():
    out = [HEAD]
    for name, fields in VARIANTS.items():
        out.append("pub struct %s {" % name)
        for f, t in fields:
            out.append("    %s: %s" % (f, t))
        out.append("}")
        out.append("")
        out.append("pub fn %s_new(id: Int, kind: Str, scope_id: Int) -> %s {" % (name, name))
        out.append("    return %s {" % name)
        for i, (f, t) in enumerate(fields):
            comma = "," if i < len(fields) - 1 else ""
            out.append("        %s: %s%s" % (f, literal_value(f, t), comma))
        out.append("    }")
        out.append("}")
        out.append("")
        out.append("fn %s_scope_id(view x: %s) -> Int => x.scope_id" % (name, name))
        for f, t in fields:
            if t == "Bool":
                out.append("fn %s_%s(view x: %s) -> Bool => x.%s" % (name, f, name, f))
        out.append("")

    out.append("fn main() {")
    out.append("    mut i = 0")
    for name, fields in VARIANTS.items():
        bools = [f for f, t in fields if t == "Bool"]
        out.append('    println("=== %s ===")' % name)
        out.append("    mut xs: List<%s> = []" % name)
        out.append("    i = 0")
        out.append("    while i < 3 {")
        out.append('        xs = xs.push(%s_new(i, "K", i))' % name)
        out.append("        i = i + 1")
        out.append("    }")
        out.append("    i = 0")
        out.append("    while i < xs.len() {")
        out.append("        let x = xs[i]")
        pieces = ['"  i=" + int_to_str(i)', '" scope_id=" + int_to_str(%s_scope_id(x))' % name]
        for f in bools:
            pieces.append('" %s=" + b2s(%s_%s(x))' % (f, name, f))
        out.append("        println(" + " + ".join(pieces) + ")")
        out.append("        i = i + 1")
        out.append("    }")
    out.append("}")
    out.append("")

    p = pathlib.Path("probes/bool_field/main.dtr")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(out), encoding="utf-8")
    print("wrote", p, "with", len(VARIANTS), "variants")


if __name__ == "__main__":
    main()
