#!/usr/bin/env python3
"""Generate one isolated project per struct layout under probes/layout_iso/.

The bisect in probes/bool_field put all layouts in one file and produced
contradictory results: an exact copy of `Subscription` was correct there but
broken in the kernel. That points at cross-struct interference rather than an
inherently bad layout, so each layout is emitted into its own project here.
"""

import pathlib

VARIANTS = {
    "V0_exact_subscription": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Bool"),
        ("cancelled", "Bool"), ("delivery_count", "Int"), ("muted", "List<Str>"),
    ],
    "V1_no_muted": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Bool"),
        ("cancelled", "Bool"), ("delivery_count", "Int"),
    ],
    "V2_bools_last": [
        ("id", "Int"), ("kind", "Str"), ("scope_id", "Int"),
        ("deferred_mode", "Bool"), ("cancelled", "Bool"),
    ],
    "V3_bools_then_int": [
        ("id", "Int"), ("kind", "Str"), ("scope_id", "Int"),
        ("deferred_mode", "Bool"), ("cancelled", "Bool"), ("delivery_count", "Int"),
    ],
    "V4_bools_as_int": [
        ("id", "Int"), ("kind", "Str"), ("subsystem", "Str"), ("priority", "Int"),
        ("scope", "Str"), ("scope_id", "Int"), ("deferred_mode", "Int"),
        ("cancelled", "Int"), ("delivery_count", "Int"), ("muted", "List<Str>"),
    ],
    "V5_one_bool_last": [
        ("id", "Int"), ("kind", "Str"), ("scope_id", "Int"), ("deferred_mode", "Bool"),
    ],
    "V6_one_bool_mid": [
        ("id", "Int"), ("kind", "Str"), ("deferred_mode", "Bool"), ("scope_id", "Int"),
    ],
}


def literal_value(field, typ):
    return {
        "id": "id", "kind": "kind", "scope_id": "scope_id",
        "subsystem": '""', "priority": "10", "scope": '"document"', "muted": "[]",
    }.get(field, "false" if typ == "Bool" else "0")


def build(name, fields):
    out = ['//! GENERATED by scripts/gen_layout_iso.py - one layout per project.']
    out.append("")
    out.append("pub struct %s {" % name)
    for f, t in fields:
        out.append("    %s: %s" % (f, t))
    out.append("}")
    out.append("")
    out.append("pub fn s_new(id: Int, kind: Str, scope_id: Int) -> %s {" % name)
    out.append("    return %s {" % name)
    for i, (f, t) in enumerate(fields):
        comma = "," if i < len(fields) - 1 else ""
        out.append("        %s: %s%s" % (f, literal_value(f, t), comma))
    out.append("    }")
    out.append("}")
    out.append("")
    for f, t in fields:
        out.append("fn get_%s(view x: %s) -> %s => x.%s" % (f, name, t, f))
    out.append("")
    out.append("fn b2s(v: Bool) -> Str {")
    out.append('    mut res = "false"')
    out.append("    if v {")
    out.append('        res = "true"')
    out.append("    }")
    out.append("    return res")
    out.append("}")
    out.append("")
    out.append("fn main() {")
    out.append("    mut xs: List<%s> = []" % name)
    out.append("    mut i = 0")
    out.append("    while i < 3 {")
    out.append('        xs = xs.push(s_new(i, "K", i))')
    out.append("        i = i + 1")
    out.append("    }")
    out.append("    i = 0")
    out.append("    while i < xs.len() {")
    out.append("        let x = xs[i]")
    pieces = ['"i=" + int_to_str(i)']
    for f, t in fields:
        if t == "Bool":
            pieces.append('" %s=" + b2s(get_%s(x))' % (f, f))
        elif f == "scope_id":
            pieces.append('" scope_id=" + int_to_str(get_%s(x))' % f)
    out.append("        println(" + " + ".join(pieces) + ")")
    out.append("        i = i + 1")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


root = pathlib.Path("probes/layout_iso")
root.mkdir(parents=True, exist_ok=True)
for name, fields in VARIANTS.items():
    d = root / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "main.dtr").write_text(build(name, fields), encoding="utf-8")
    print("wrote", d / "main.dtr")
